### ISSUE TITLE
"openshift/ruby-24-centos7" is not found.

### ISSUE THREAD

**Issue by stqp** [sclorg/ruby-ex#24]
I run below command,

     $ oc new-app openshift/ruby-24-centos7~https://github.com/< yourusername >/ruby-ex 
and got an error. I think `openshift/ruby-24-centos7` should be `centos/ruby-24-centos7` or `openshift/ruby-20-centos7`,  shouldn't it? 

    $  oc new-app openshift/ruby-24-centos7~https://github.com/stqp/ruby-ex 
    error: unable to locate any images in image streams, local docker images with name "openshift/ruby-24-centos7"

    The 'oc new-app' command will match arguments to the following types:

      1. Images tagged into image streams in the current project or the 'openshift' project
         - if you don't specify a tag, we'll add ':latest'
      2. Images in the Docker Hub, on remote registries, or on the local Docker engine
      3. Templates in the current project or the 'openshift' project
      4. Git repository URLs or local paths that point to Git repositories

    --allow-missing-images can be used to point to an image that does not exist yet.

    See 'oc new-app -h' for examples.
    $

**Comment by agajdosi** [comment]
Just saw now that I am also missing openshift/ruby-24-centos7 image in my streams. They probably renamed them in the imagestream, now the image is named `openshift/ruby`. If you have the centos-imagestreams installed, you can try to run:

```
oc new-app openshift/ruby~https://github.com/< yourusername >/ruby-ex
```
